### ISSUE TITLE
Multi-protocol access to foreign git repositories

### ISSUE THREAD

**Issue by gshuflin** [coralogix/protofetch#102]
Re: https://github.com/coralogix/protofetch/pull/101#issuecomment-1719456188 , this problem - that some people use `ssh` and other people use `https` to access the same repo - is a problem in my organization. I was hoping that this closed PR would be the first step of a solution, with a follow-up PR to come that would allow `protofetch.toml` to specify multiple `url` entries, e.g. something like:

```
[another-name]
url = ["ssh://github.com/org/dep3", "https://github.com/org/dep3"]
revision = "a16f097eab6e64f2b711fd4b977e610791376223"
transitive = true
```

Another use case that we have is optionally providing a file path for a repository, so that in CI we can have one build step fetch the foreign repository and write it somewhere, and then give `protofetch` that local path, so `protofetch` does not attempt to fetch that repository itself, without breaking local workflows where we want `protofetch` to attempt the git fetch itself. I was imagining this might look like:

```
[another-name]
url = ["ssh://github.com/org/dep3", "https://github.com/org/dep3", "file:///tmp/repos/dep3"]
revision = "a16f097eab6e64f2b711fd4b977e610791376223"
transitive = true
```
Since https://github.com/coralogix/protofetch/pull/101 was closed I thought it would be good to open an explicit discussion about how to solve these problems in way that can get merged upstream.

**Comment by rtimush** [comment]
@gshuflin sorry for a delayed answer. That's a very welcome discussion, and I'd say it's a real pain point for people using protofetch.

One can use git url overrides as a workaround:
```toml
# in ~/.config/git/config
[url "git@github.com:"]
	insteadOf = "https://github.com/"
```
but I agree that it would be better if protofetch handled it better itself.

My view of this problem is that `protofetch.toml` should specify _where_ the dependencies are located, but not _how_ to fetch them. _How_ is an individual choice and therefore should be configured locally. Because of that, in my opinion we should deprecate/remove the `protocol` field from the `protofetch.toml` file, and make it locally configurable in some `~/.config/protofetch/config` file.

I would probably only have an option to configure the default protocol. Advanced use cases, like the one with a local path on CI, or using different protocols for different git servers, can still be solved by git configuration.

What do you think?
